const enEN = {
  "welcome" : "Welcome!",
  "add_contact" : "Add contact!",
  "delete_contact": "Delete contact!",
  "send_message" : "Write a message!",
  'create_chat': 'Create a new chat!',
  'error': "Error command entered!",
  'settings': "Settings",
  'exit': "EXIT",
  "success_set": "Successfully installed!",
  "number_short":"The phone number is short!",
  "number_long":"The phone number is long!",
  "phone":"Enter a phone number!",
  "name":"Write the name!",
  "error_number":"An error in the number!",
  "try_agin":"Try again!",
  "uzb":"To select Uzbek language!",
  "rus":"To select Russian language!",
  "eng":"To select English language!",
  "password_confirm":"Confirm Password!",
  "password_update":" Updated password?",
  "password_delete":"Can you delete password?",
  "account_lock":"The device is blocked!",
  "password_set":"Set a password!",
  "change_lang":"Change language !",
  "change_pasw":"Security Department!",
  "success_update":"Successfully updated!",
  "who" : "Who do you want to send a message to? ",
  "id" : "Enter your ID!!",
  "instruction" : "Write a message, if you want to send it, write '>' at the end of the message !\n check message 'check'\ncancel 'off",
  "chose" : "Choose!",
  "delete_all" : "Delete all contacts!",
  "delete_one" : "Delete Contact!",
  "contact" : "Contacts",
  "back" : "Back!",
  "back_home" : "Main menu!",
  "yes" : "Yes!",
  "no" : "No!",
  "empty":"Page is Empty",
  "password_not_found" : "Password not set!",
  "password_update!":" Updated password!",
  "password_delete!":"Delete password!",
  "password_set!": "Set password!",
  "id_": "Delete ID!",
  "read_all": "View all contacts!",
};