const uzUZ = {
  "welcome": "Hush kelibsiz!",
  "empty": "Fayl bo'sh",
  "contact": "Contactlar!",
  "add_contact": "Contact qushish!",
  "delete_contact": "Contact ochirish!",
  "send_message": "Xabar yozish!",
  "chose": "Tanlang!",
  "back": "Orqaga qaytish!",
  "back_home": "Bosh  menyuga qaytish!",
  'create_chat': 'Yangi chat yaratish.',
  'error': "Xato buyruq kiritildi",
  'settings': "Sozlamalar",
  'exit': "Dasturdan chiqish.",
  "success_set": "Muvaffaqiyatli urnatildi!",
  "number_short": "Telefon raqami  qisqa!",
  "number_long": "Telefon raqami  uzun!",
  "phone": "Telefon raqam kiritng!",
  "name": "Ism kitiring!",
  "error_number": "Raqamda xatolik!",
  "try_agin": "qayta urinib ko'ring!",
  "uzb": "Uzbek tilini tanlash uchun!",
  "rus": "Rus tilini tanlash uchun!",
  "eng": "Ingliz tilini tanlash uchun!",
  "password_delete": "Parolni ochirmoqchimisiz?",
  "password_update": "Parol yangilamoqchimisiz?",
  "password_confirm": "Parolni tasdiqlang!",
  "account_lock": "Qurilma bloklandi!",
  "password_set": "Parol urnating!",
  "change_lang": "Til o'zgartirish!",
  "change_pasw": "Xafsizlik bo'limi!",
  "success_update": "Muvaffaqiyatli yangilandi!",
  "who": "Kimga xabar junatmoqchisiz?",
  "id": "Oziz ID-yizzi kiriting!",
  "instruction":
  "Xabarni yozing junatmoqchi bulsangiz xabar oxiriga '>' yozing!\nYangi xabar tekshirish uchun 'check'\nChiqish uchun 'off'",
  "delete_all": "Hamma contactlarni ochirish!",
  "delete_one": "Contact ochirish!",
  "yes": "Ha!",
  "no": "Yoq!",
  "password_not_found": "Parol ornatilmagan!",
  "password_delete!": "Parolni ochirish!",
  "password_update!": "Parol yangilash!",
  "password_set!": "Parol otnatsh!",
  "id_": "ID ni ochirish!",
  "read_all": "Hamma contactlarni korish!",
};
